// register

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SET_ALERT = "SET_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const LOGOUT = "LOGOUT";

export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAIL = "UPDATE_FAIL";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";

export const RESET_UPDATE = "RESET_UPDATE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SHOW_TOAST = "SHOW_TOAST";
export const HIDE_TOAST = "HIDE_TOAST";

export const CHECK_REGISTERED = "CHECK_REGISTERED";
export const CHECK_UNREGISTERED = "CHECK_UNREGISTERED";

export const RESET_PASSWORD_EMAIL_SENT = "RESET_PASSWORD_EMAIL_SENT";
export const RESET_PASSWORD_EMAIL_NOT_SENT = "RESET_PASSWORD_EMAIL_NOT_SENT";

export const RESET_PASSWORD_VALID_UID = "RESET_PASSWORD_VALID_UID";
export const RESET_PASSWORD_INVALID_UID = "RESET_PASSWORD_INVALID_UID";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const TOKEN_REFRESH = "TOKEN_REFRESH";
